# Generated by Django 6.0.1 on 2026-02-05 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='name',
            new_name='artist_name',
        ),
        migrations.RenameField(
            model_name='gig',
            old_name='artist',
            new_name='artist_name',
        ),
        migrations.RenameField(
            model_name='gig',
            old_name='venue',
            new_name='venue_name',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='name',
            new_name='venue_name',
        ),
        migrations.AlterUniqueTogether(
            name='gig',
            unique_together={('artist_name', 'venue_name', 'gig_date')},
        ),
    ]
