# Generated by Django 6.0.1 on 2026-02-05 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0002_rename_name_artist_artist_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='artist_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='gig',
            old_name='artist_name',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='gig',
            old_name='venue_name',
            new_name='venue',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='venue_name',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='gig',
            unique_together={('artist', 'venue', 'gig_date')},
        ),
    ]
