# Generated by Django 5.2.4 on 2026-02-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0004_venue_set_time_alter_artist_id_alter_gig_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='set_time',
        ),
        migrations.AddField(
            model_name='gig',
            name='play_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which venues are displayed'),
        ),
    ]
