# Generated by Django 5.2.4 on 2026-02-07 12:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0005_remove_venue_set_time_gig_play_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='artist_logos'),
        ),
    ]
