# Generated by Django 5.2.4 on 2026-02-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0007_alter_artist_id_alter_gig_id_alter_venue_id_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cover_processing_fees',
            field=models.BooleanField(default=False),
        ),
    ]
