# Generated by Django 5.2.4 on 2026-02-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0008_payment_cover_processing_fees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='cover_processing_fees',
        ),
        migrations.AddField(
            model_name='gig',
            name='cover_processing_fees',
            field=models.BooleanField(default=False, help_text='If true, MT will cover payment processing fees for this gig'),
        ),
    ]
