# Generated by Django 5.2.4 on 2026-02-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0009_remove_payment_cover_processing_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='processor_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
