# Generated by Django 5.2.4 on 2026-02-18 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0010_payment_processor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('format', models.CharField(choices=[('poster', 'Poster'), ('card', 'Card')], max_length=20)),
                ('fee_model', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_events', to='gigs.gig')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.PositiveIntegerField(help_text='Amount in pence')),
                ('status', models.CharField(choices=[('created', 'Created'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('scan_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='gigs.scanevent')),
            ],
        ),
        migrations.AddConstraint(
            model_name='scanevent',
            constraint=models.UniqueConstraint(fields=('gig', 'session_key'), name='unique_scan_per_session_per_gig'),
        ),
    ]
