# Generated by Django 5.2.4 on 2026-04-12 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0011_scanevent_paymentintent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintent',
            name='scan_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intents', to='gigs.scanevent'),
        ),
    ]
