# Generated by Django 5.2.4 on 2026-04-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0012_alter_paymentintent_scan_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='is_repeat',
            field=models.BooleanField(default=False),
        ),
    ]
