# Generated by Django 5.2.4 on 2026-04-13 08:09

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0013_paymentintent_is_repeat'),
    ]

    operations = [
    migrations.AlterField(
        model_name='paymentintent',
        name='scan_event',
        field=models.ForeignKey(
            to='gigs.scanevent',
            on_delete=models.SET_NULL,
            null=True,
            blank=True,
            related_name='payment_intents'
        ),
    ),
]
