# Generated by Django 5.2.4 on 2026-04-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0014_auto_20260413_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tip_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
