# Generated by Django 5.2.4 on 2026-04-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0015_payment_tip_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanevent',
            name='format',
            field=models.CharField(choices=[('poster', 'Poster'), ('card', 'Card'), ('unknown', 'Unknown')], max_length=20),
        ),
    ]
