# Generated by Django 5.2.4 on 2026-05-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0016_alter_scanevent_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='If true, disables Stripe payments and reporting metrics for this gig'),
        ),
    ]
